# Generated by Django 2.2.16 on 2023-02-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230209_1643'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_members',
        ),
    ]
