# Generated by Django 2.2.16 on 2023-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230209_1759'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_members',
        ),
    ]
